[project]
name = "3DGS-cuda128"
version = "0.1.0"
description = "3dgs and torch and xformers at latest cuda (12.8)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diff-gaussian-rasterization",
    "tqdm",
    "hydra-core",
    "jaxtyping",
    "einops",
    "scikit-image",
    "matplotlib",
    "imageio",
    "lpips",
    "e3nn",
    "plyfile",
    "xformers>=0.0.33.post1",
    "torch>=2",
    "torchvision>=0.24.0",
    "opencv-python>=4.12.0.88",
    "openexr>=3.4.4",
    "imath>=0.0.2",
    "beartype>=0.22.9",
]

[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = false
no-build-isolation-package = ["diff-gaussian-rasterization"]

[tool.uv.sources]
diff-gaussian-rasterization = { path = "submodules/diff-gaussian-rasterization" }

[dependency-groups]
test = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore:.*warmup, rep, and use_cuda_graph parameters are deprecated.*:DeprecationWarning:triton.runtime.autotuner",
]

[tool.ruff]
src = ["src"]

[tool.ruff.lint.isort]
combine-as-imports = true


